### ISSUE TITLE
客户端无法调到1920

### ISSUE THREAD

**Issue by yylike-code** [Happyroots/Teamfighting-Tactics-script#1]
进游戏是1080，但是外面的客户端最大只能调到1600怎么破，一直提示
“寻找未开标志图片0图片失败
寻找游戏中图片1图片失败
没找到对应的状态图片”

**Comment by Happyroots** [comment]
请问只是外面的客户端无法识别，从而无法自动开局和继续游戏吗？
可以尝试自己截取自己客户端相应的分辨率的图片，替换掉脚本文件夹内的相应的匹配图片。
因为OPEN＿CV匹配图片时要求匹配的目标　大小　也得一样

**Comment by yylike-code** [comment]
> 请问只是外面的客户端无法识别，从而无法自动开局和继续游戏吗？ 可以尝试自己截取自己客户端相应的分辨率的图片，替换掉脚本文件夹内的相应的匹配图片。 因为OPEN＿CV匹配图片时要求匹配的目标　大小　也得一样

对，是外面的客户端，只能设置到1600x900。我参考“python图像识别自动化脚本”里的使用说明书，补全了依赖包，故障依旧。
尝试重新截图来替换文件夹中的“findgame.png”，问题并没有解决。
而且出现了新问题，在运行时会先提示以下信息：
[ WARN:0@5.293] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('pic/娓告垙鏈紑鍒ゆ柇0.png'): can't open/read file: check file path/integrity
寻找未开标志图片0图片失败
[ WARN:0@5.324] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('pic/娓告垙涓垽鏂?寻找游戏中图片1图片失败

**Comment by Happyroots** [comment]
读取的图片名字不能是中文，你设置的图片名字是中文吗
还有图片命名首写字母不能用大写英文，比如之前图片命名为：Img1.png；改变后：img1.png，就可以读入了。
![image](https://user-images.githubusercontent.com/90665513/161384250-c30c580c-4736-41a7-a7af-1bfc2194c05f.png)
这个是我的外面的客户端大小，并不是1920*1080

**Comment by yylike-code** [comment]
感谢及时解答。目前是直接下载的zip解压的，所有都没有动过。看了下代码里是 “一费英雄.png”，但是文件夹里是1hreo.png这种形式。是需要改成一样的吗？
![image](https://user-images.githubusercontent.com/65947174/161385473-a28ac5a1-335c-4016-bfca-2718c04cd742.png)

**Comment by Happyroots** [comment]
是的，图片名字不能是中文，需要改成英文一样的
[TFT_Assistant.py](https://github.com/Happyroots/Teamfighting-Tactics-script/blob/main/%E4%BA%91%E9%A1%B6%E8%84%9A%E6%9C%AC.V2/TFT_Assistant.py)
是这个文件，你估计运行错了

**Comment by yylike-code** [comment]
折腾了一下，正常使用了，喜提七天。不过整体功能还是正常的，加油大佬

**Comment by Happyroots** [comment]
嗯嗯，我主要是刷几局过一下任务，自己刷费眼费时。共同加油！

**Comment by yylike-code** [comment]
大胆猜测，x迅是通过每局排名和阵容来判断是否为脚本的。看来还是得更智能，太难了。
